apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app.kubernetes.io/part-of: "GitHubSelfHostedRunner"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
        app.kubernetes.io/part-of: "GitHubSelfHostedRunner"
    spec:
      serviceAccountName: {{ .Values.name }}-sa
      containers:
        - name: {{ .Values.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
          securityContext:
            allowPrivilegeEscalation: true
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu | default "500m" }}
              memory: {{ .Values.resources.requests.memory | default "700Mi" }}
              ephemeral-storage: {{ .Values.resources.requests.ephemeralstorage | default "2Gi" }}
            limits:
              cpu: {{ .Values.resources.limits.cpu | default "800m" }}
              memory: {{ .Values.resources.limits.memory | default "1Gi" }}
              ephemeral-storage: {{ .Values.resources.limits.ephemeralstorage | default "10Gi" }}
          envFrom:
            # Attach all key-value pairs from the Secret as environment variables
            - secretRef:
                name: {{ .Values.name }}-secret
      securityContext:
        runAsUser: 1000
        runAsNonRoot: true
      {{- if .Values.image.imagePullSecretName }}
      imagePullSecrets:
        - name: {{ .Values.image.imagePullSecretName }}
      {{- end }}