apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-secret
  annotations:
    "helm.sh/resource-policy": keep # Keep secret even if the parent chart is deleted.
type: Opaque
{{- if .Values.secrets }}
stringData:
{{ toYaml .Values.secrets | indent 2 }}
{{- end }}
