### Stage 1 - builder
FROM registry.access.redhat.com/ubi9/ubi-minimal:latest AS builder

ARG TKN_VERSION=0.43.0
ARG RUNNER_VERSION=2.335.1

ENV TKN_URL="https://github.com/tektoncd/cli/releases/download/v${TKN_VERSION}/tkn_${TKN_VERSION}_Linux_x86_64.tar.gz" \
    RUNNER_URL="https://github.com/actions/runner/releases/download/v${RUNNER_VERSION}/actions-runner-linux-x64-${RUNNER_VERSION}.tar.gz"

RUN microdnf -y install tar gzip

WORKDIR /tmp/

RUN curl -fL "$TKN_URL" -o /tmp/tkn.tar.gz && \
    curl -fL "$RUNNER_URL" -o /tmp/runner.tar.gz && \
    mkdir tkn runner && \
    tar -xzf tkn.tar.gz --directory tkn && \
    tar -xzf runner.tar.gz --directory runner

### Stage 2
FROM registry.access.redhat.com/ubi9/ubi-minimal:latest

USER root

## Packages installed for the runner
RUN microdnf update -y && \
    microdnf install -y \
    # .NET runtime deps (required by GitHub Actions runner)
    lttng-ust openssl-libs krb5-libs zlib libicu \
    # TLS/crypto
    openssl \
    # Container build tools
    podman buildah \
    # Additional user tools
    jq git tar gzip \
    && microdnf clean all

# Copy artifacts from builder
COPY --from=builder --chmod=0755 /tmp/tkn/tkn /usr/local/bin
COPY --from=builder /tmp/runner/ /home/runner/

COPY --chmod=644 etc-containers-storage.conf /etc/containers/storage.conf

# Working directory for github actions runner
WORKDIR /home/runner

RUN adduser --uid 1000 --no-create-home runner && \
    chmod -Rf 775 /home/runner/ && \
    chown -Rf runner:0 /home/runner/

ENV HOME=/home/runner

# runner user to run since GH Runner does not support running as root and user is needed to run buildah
USER 1000

ENV BUILDAH_ISOLATION=chroot
